import { TestCycle, TestRunItem, FolderWithStats } from "./types";

// Helper to get timestamps relative to current date
// This ensures mock data always appears in recent date ranges
function getRelativeTimestamp(daysAgo: number, hoursAgo: number = 0): number {
  const now = Date.now();
  const daysMs = daysAgo * 24 * 60 * 60 * 1000;
  const hoursMs = hoursAgo * 60 * 60 * 1000;
  return now - daysMs - hoursMs;
}

// Mock Test Cycles with dynamic timestamps
export const mockTestCycles: TestCycle[] = [
  {
    ID: 201,
    key: "DEMO-CY-201",
    title: "Sprint 15 - User Authentication & Profile",
    objective: "Test user login, registration, and profile management features",
    folder: {
      ID: 801,
      name: "Sprint 15 - Current Sprint",
      description: "Current sprint testing",
      parentID: 800,
    },
    ownedByID: "user-001",
    closedByID: null,
    startDate: getRelativeTimestamp(14),
    endDate: getRelativeTimestamp(-14),
    createdDate: getRelativeTimestamp(14),
    updatedDate: getRelativeTimestamp(1),
    isClosed: false,
    isArchived: false,
  },
  {
    ID: 202,
    key: "DEMO-CY-202",
    title: "Sprint 15 - Payment Gateway Integration",
    objective: "Test payment processing, refunds, and transaction history",
    folder: {
      ID: 801,
      name: "Sprint 15 - Current Sprint",
      description: "Current sprint testing",
      parentID: 800,
    },
    ownedByID: "user-002",
    closedByID: null,
    startDate: getRelativeTimestamp(14),
    endDate: getRelativeTimestamp(-14),
    createdDate: getRelativeTimestamp(14),
    updatedDate: getRelativeTimestamp(2),
    isClosed: false,
    isArchived: false,
  },
  {
    ID: 203,
    key: "DEMO-CY-203",
    title: "Sprint 15 - Notification System",
    objective: "Test email, SMS, and push notification delivery",
    folder: {
      ID: 801,
      name: "Sprint 15 - Current Sprint",
      description: "Current sprint testing",
      parentID: 800,
    },
    ownedByID: "user-003",
    closedByID: null,
    startDate: getRelativeTimestamp(14),
    endDate: getRelativeTimestamp(-14),
    createdDate: getRelativeTimestamp(14),
    updatedDate: getRelativeTimestamp(3),
    isClosed: false,
    isArchived: false,
  },
  {
    ID: 204,
    key: "DEMO-CY-204",
    title: "Sprint 14 - Shopping Cart & Checkout",
    objective: "Regression testing for shopping cart and checkout flow",
    folder: {
      ID: 802,
      name: "Sprint 14 - Previous Sprint",
      description: "Previous sprint",
      parentID: 800,
    },
    ownedByID: "user-001",
    closedByID: "user-001",
    startDate: getRelativeTimestamp(28),
    endDate: getRelativeTimestamp(14),
    createdDate: getRelativeTimestamp(28),
    updatedDate: getRelativeTimestamp(14),
    isClosed: true,
    isArchived: false,
  },
  {
    ID: 205,
    key: "DEMO-CY-205",
    title: "Sprint 14 - Search & Filter Features",
    objective: "Test product search, filters, and sorting functionality",
    folder: {
      ID: 802,
      name: "Sprint 14 - Previous Sprint",
      description: "Previous sprint",
      parentID: 800,
    },
    ownedByID: "user-002",
    closedByID: "user-002",
    startDate: getRelativeTimestamp(28),
    endDate: getRelativeTimestamp(14),
    createdDate: getRelativeTimestamp(28),
    updatedDate: getRelativeTimestamp(14),
    isClosed: true,
    isArchived: false,
  },
  {
    ID: 206,
    key: "DEMO-CY-206",
    title: "Sprint 13 - Admin Dashboard",
    objective: "Test admin panel features and user management",
    folder: {
      ID: 803,
      name: "Sprint 13 - Completed",
      description: "Completed sprint",
      parentID: 800,
    },
    ownedByID: "user-003",
    closedByID: "user-003",
    startDate: getRelativeTimestamp(42),
    endDate: getRelativeTimestamp(28),
    createdDate: getRelativeTimestamp(42),
    updatedDate: getRelativeTimestamp(28),
    isClosed: true,
    isArchived: false,
  },
  {
    ID: 207,
    key: "DEMO-CY-207",
    title: "Sprint 13 - Reporting Module",
    objective: "Test report generation, export, and scheduling",
    folder: {
      ID: 803,
      name: "Sprint 13 - Completed",
      description: "Completed sprint",
      parentID: 800,
    },
    ownedByID: "user-001",
    closedByID: "user-001",
    startDate: getRelativeTimestamp(42),
    endDate: getRelativeTimestamp(28),
    createdDate: getRelativeTimestamp(42),
    updatedDate: getRelativeTimestamp(28),
    isClosed: true,
    isArchived: false,
  },
  {
    ID: 208,
    key: "DEMO-CY-208",
    title: "Regression Test - Core Features",
    objective: "Full regression testing of core application features",
    folder: {
      ID: 804,
      name: "Regression Testing",
      description: "Ongoing regression tests",
      parentID: 800,
    },
    ownedByID: "user-002",
    closedByID: null,
    startDate: getRelativeTimestamp(14),
    endDate: null,
    createdDate: getRelativeTimestamp(14),
    updatedDate: getRelativeTimestamp(0),
    isClosed: false,
    isArchived: false,
  },
  {
    ID: 209,
    key: "DEMO-CY-209",
    title: "Security Testing - Authentication",
    objective: "Security audit of authentication and authorization",
    folder: {
      ID: 805,
      name: "Security Testing",
      description: "Security and penetration testing",
      parentID: 800,
    },
    ownedByID: "user-003",
    closedByID: null,
    startDate: getRelativeTimestamp(13),
    endDate: getRelativeTimestamp(-14),
    createdDate: getRelativeTimestamp(13),
    updatedDate: getRelativeTimestamp(0),
    isClosed: false,
    isArchived: false,
  },
  {
    ID: 210,
    key: "DEMO-CY-210",
    title: "Performance Testing - Load Test",
    objective: "Test system performance under high load conditions",
    folder: {
      ID: 806,
      name: "Performance Testing",
      description: "Performance and load testing",
      parentID: 800,
    },
    ownedByID: "user-001",
    closedByID: null,
    startDate: getRelativeTimestamp(12),
    endDate: getRelativeTimestamp(-14),
    createdDate: getRelativeTimestamp(12),
    updatedDate: getRelativeTimestamp(0),
    isClosed: false,
    isArchived: false,
  },
];

// Mock Test Runs with dynamic timestamps spread across last 13 days
export const mockTestRuns: TestRunItem[] = [
  // Day 1 (13 days ago) - Authentication Tests
  {
    ID: 5001,
    testCase: {
      ID: 1001,
      key: "DEMO-TC-1001",
      title: "User Login with Valid Credentials",
      description: "Test user can login with correct email and password",
      precondition: "User account exists in database",
      status: { name: "Ready", description: "Ready for execution" },
      priority: { name: "Critical" },
    },
    assignedToID: "user-001",
    assignmentDate: getRelativeTimestamp(14),
    runs: [
      {
        ID: 10001,
        testRunKey: "DEMO-R-10001",
        testCaseID: 1001,
        status: "Passed",
        executedByID: "user-001",
        executionDate: getRelativeTimestamp(13, 10),
        updatedDate: getRelativeTimestamp(13, 10),
        executionTime: 45000,
        environment: "Production",
        buildNumber: "v2.5.0",
        comment: "Login successful, redirected to dashboard",
      },
    ],
  },
  {
    ID: 5002,
    testCase: {
      ID: 1002,
      key: "DEMO-TC-1002",
      title: "User Login with Invalid Password",
      description: "Test system shows error when password is incorrect",
      precondition: "User account exists",
      status: { name: "Ready", description: "" },
      priority: { name: "High" },
    },
    assignedToID: "user-001",
    assignmentDate: getRelativeTimestamp(14),
    runs: [
      {
        ID: 10002,
        testRunKey: "DEMO-R-10002",
        testCaseID: 1002,
        status: "Passed",
        executedByID: "user-001",
        executionDate: getRelativeTimestamp(13, 9),
        updatedDate: getRelativeTimestamp(13, 9),
        executionTime: 32000,
        environment: "Production",
        buildNumber: "v2.5.0",
        comment: "Error message displayed correctly",
      },
    ],
  },
  // Day 2 (12 days ago) - More Authentication
  {
    ID: 5003,
    testCase: {
      ID: 1003,
      key: "DEMO-TC-1003",
      title: "User Registration with New Email",
      description: "Test new user can register with unique email",
      precondition: "Email not already registered",
      status: { name: "Ready", description: "" },
      priority: { name: "Critical" },
    },
    assignedToID: "user-002",
    assignmentDate: getRelativeTimestamp(14),
    runs: [
      {
        ID: 10003,
        testRunKey: "DEMO-R-10003",
        testCaseID: 1003,
        status: "Failed",
        executedByID: "user-002",
        executionDate: getRelativeTimestamp(12, 14),
        updatedDate: getRelativeTimestamp(12, 14),
        executionTime: 78000,
        environment: "Staging",
        buildNumber: "v2.5.0",
        comment: "Verification email not sent. Issue logged as DEMO-BUG-234",
      },
    ],
  },
  {
    ID: 5004,
    testCase: {
      ID: 1004,
      key: "DEMO-TC-1004",
      title: "Password Reset Flow",
      description: "Test user can reset password via email link",
      precondition: "User account exists",
      status: { name: "Ready", description: "" },
      priority: { name: "High" },
    },
    assignedToID: "user-001",
    assignmentDate: getRelativeTimestamp(14),
    runs: [
      {
        ID: 10004,
        testRunKey: "DEMO-R-10004",
        testCaseID: 1004,
        status: "Passed",
        executedByID: "user-001",
        executionDate: getRelativeTimestamp(12, 11),
        updatedDate: getRelativeTimestamp(12, 11),
        executionTime: 125000,
        environment: "Production",
        buildNumber: "v2.5.0",
        comment: "Reset email received and password updated successfully",
      },
    ],
  },
  // Day 3 (11 days ago) - Profile tests
  {
    ID: 5005,
    testCase: {
      ID: 1005,
      key: "DEMO-TC-1005",
      title: "Profile Picture Upload",
      description: "Test user can upload and update profile picture",
      precondition: "User logged in",
      status: { name: "Ready", description: "" },
      priority: { name: "Medium" },
    },
    assignedToID: "user-002",
    assignmentDate: getRelativeTimestamp(14),
    runs: [
      {
        ID: 10005,
        testRunKey: "DEMO-R-10005",
        testCaseID: 1005,
        status: "Blocked",
        executedByID: "user-002",
        executionDate: getRelativeTimestamp(11, 13),
        updatedDate: getRelativeTimestamp(11, 13),
        executionTime: 0,
        environment: "Staging",
        buildNumber: "v2.5.0",
        comment: "Image upload service is down. Cannot test.",
      },
    ],
  },
  // Day 4 (10 days ago) - Payment Tests
  {
    ID: 5006,
    testCase: {
      ID: 2001,
      key: "DEMO-TC-2001",
      title: "Credit Card Payment Success",
      description: "Test payment processing with valid credit card",
      precondition: "Shopping cart has items, user logged in",
      status: { name: "Ready", description: "" },
      priority: { name: "Critical" },
    },
    assignedToID: "user-002",
    assignmentDate: getRelativeTimestamp(14),
    runs: [
      {
        ID: 10006,
        testRunKey: "DEMO-R-10006",
        testCaseID: 2001,
        status: "Passed",
        executedByID: "user-002",
        executionDate: getRelativeTimestamp(10, 10),
        updatedDate: getRelativeTimestamp(10, 10),
        executionTime: 156000,
        environment: "Staging",
        buildNumber: "v2.5.0",
        comment: "Payment processed, order confirmed",
      },
    ],
  },
  {
    ID: 5007,
    testCase: {
      ID: 2002,
      key: "DEMO-TC-2002",
      title: "Payment with Insufficient Funds",
      description: "Test payment fails when card has insufficient funds",
      precondition: "Shopping cart has items",
      status: { name: "Ready", description: "" },
      priority: { name: "High" },
    },
    assignedToID: "user-002",
    assignmentDate: getRelativeTimestamp(14),
    runs: [
      {
        ID: 10007,
        testRunKey: "DEMO-R-10007",
        testCaseID: 2002,
        status: "Passed",
        executedByID: "user-002",
        executionDate: getRelativeTimestamp(10, 9),
        updatedDate: getRelativeTimestamp(10, 9),
        executionTime: 89000,
        environment: "Staging",
        buildNumber: "v2.5.0",
        comment: "Error message displayed, payment declined",
      },
    ],
  },
  // Day 5 (9 days ago) - More payment tests
  {
    ID: 5008,
    testCase: {
      ID: 2003,
      key: "DEMO-TC-2003",
      title: "Refund Processing",
      description: "Test refund can be initiated and processed",
      precondition: "Order exists and eligible for refund",
      status: { name: "Ready", description: "" },
      priority: { name: "High" },
    },
    assignedToID: "user-003",
    assignmentDate: getRelativeTimestamp(14),
    runs: [
      {
        ID: 10008,
        testRunKey: "DEMO-R-10008",
        testCaseID: 2003,
        status: "Failed",
        executedByID: "user-003",
        executionDate: getRelativeTimestamp(9, 14),
        updatedDate: getRelativeTimestamp(9, 14),
        executionTime: 234000,
        environment: "Staging",
        buildNumber: "v2.5.0",
        comment: "Refund amount calculation incorrect. Bug reported: DEMO-BUG-235",
      },
    ],
  },
  {
    ID: 5009,
    testCase: {
      ID: 2004,
      key: "DEMO-TC-2004",
      title: "Transaction History Display",
      description: "Test user can view complete transaction history",
      precondition: "User has previous transactions",
      status: { name: "Ready", description: "" },
      priority: { name: "Medium" },
    },
    assignedToID: "user-002",
    assignmentDate: getRelativeTimestamp(14),
    runs: [
      {
        ID: 10009,
        testRunKey: "DEMO-R-10009",
        testCaseID: 2004,
        status: "Passed",
        executedByID: "user-002",
        executionDate: getRelativeTimestamp(9, 11),
        updatedDate: getRelativeTimestamp(9, 11),
        executionTime: 67000,
        environment: "Production",
        buildNumber: "v2.5.0",
        comment: "All transactions displayed with correct details",
      },
    ],
  },
  // Day 6 (8 days ago) - Notification Tests
  {
    ID: 5010,
    testCase: {
      ID: 3001,
      key: "DEMO-TC-3001",
      title: "Email Notification Delivery",
      description: "Test email notifications are sent successfully",
      precondition: "User has valid email address",
      status: { name: "Ready", description: "" },
      priority: { name: "High" },
    },
    assignedToID: "user-003",
    assignmentDate: getRelativeTimestamp(14),
    runs: [
      {
        ID: 10010,
        testRunKey: "DEMO-R-10010",
        testCaseID: 3001,
        status: "Passed",
        executedByID: "user-003",
        executionDate: getRelativeTimestamp(8, 10),
        updatedDate: getRelativeTimestamp(8, 10),
        executionTime: 95000,
        environment: "Production",
        buildNumber: "v2.5.0",
        comment: "Email received within 2 minutes",
      },
    ],
  },
  {
    ID: 5011,
    testCase: {
      ID: 3002,
      key: "DEMO-TC-3002",
      title: "SMS Notification Delivery",
      description: "Test SMS notifications are sent to mobile number",
      precondition: "User has valid phone number",
      status: { name: "Ready", description: "" },
      priority: { name: "High" },
    },
    assignedToID: "user-003",
    assignmentDate: getRelativeTimestamp(14),
    runs: [
      {
        ID: 10011,
        testRunKey: "DEMO-R-10011",
        testCaseID: 3002,
        status: "Passed",
        executedByID: "user-003",
        executionDate: getRelativeTimestamp(8, 9),
        updatedDate: getRelativeTimestamp(8, 9),
        executionTime: 78000,
        environment: "Staging",
        buildNumber: "v2.5.0",
        comment: "SMS delivered successfully",
      },
    ],
  },
  // Day 7 (7 days ago) - Push notification (not run)
  {
    ID: 5012,
    testCase: {
      ID: 3003,
      key: "DEMO-TC-3003",
      title: "Push Notification on Mobile App",
      description: "Test push notifications appear on mobile devices",
      precondition: "User has mobile app installed and notifications enabled",
      status: { name: "Ready", description: "" },
      priority: { name: "Medium" },
    },
    assignedToID: "user-003",
    assignmentDate: getRelativeTimestamp(14),
    runs: [
      {
        ID: 10012,
        testRunKey: "DEMO-R-10012",
        testCaseID: 3003,
        status: "Not Run",
        executedByID: "",
        executionDate: 0,
        updatedDate: 0,
        executionTime: 0,
        environment: "",
        buildNumber: "",
        comment: "",
      },
    ],
  },
  {
    ID: 5013,
    testCase: {
      ID: 3004,
      key: "DEMO-TC-3004",
      title: "Notification Preferences",
      description: "Test user can customize notification preferences",
      precondition: "User logged in",
      status: { name: "Ready", description: "" },
      priority: { name: "Low" },
    },
    assignedToID: "user-003",
    assignmentDate: getRelativeTimestamp(14),
    runs: [
      {
        ID: 10013,
        testRunKey: "DEMO-R-10013",
        testCaseID: 3004,
        status: "Passed",
        executedByID: "user-003",
        executionDate: getRelativeTimestamp(7, 11),
        updatedDate: getRelativeTimestamp(7, 11),
        executionTime: 45000,
        environment: "Production",
        buildNumber: "v2.5.0",
        comment: "Preferences saved and applied correctly",
      },
    ],
  },
  // Day 8 (6 days ago) - Shopping Cart Tests
  {
    ID: 5014,
    testCase: {
      ID: 4001,
      key: "DEMO-TC-4001",
      title: "Add Product to Cart",
      description: "Test user can add products to shopping cart",
      precondition: "User browsing products",
      status: { name: "Ready", description: "" },
      priority: { name: "Critical" },
    },
    assignedToID: "user-001",
    assignmentDate: getRelativeTimestamp(14),
    runs: [
      {
        ID: 10014,
        testRunKey: "DEMO-R-10014",
        testCaseID: 4001,
        status: "Passed",
        executedByID: "user-001",
        executionDate: getRelativeTimestamp(6, 14),
        updatedDate: getRelativeTimestamp(6, 14),
        executionTime: 34000,
        environment: "Production",
        buildNumber: "v2.4.5",
        comment: "Product added successfully, cart count updated",
      },
    ],
  },
  {
    ID: 5015,
    testCase: {
      ID: 4002,
      key: "DEMO-TC-4002",
      title: "Remove Product from Cart",
      description: "Test user can remove products from cart",
      precondition: "Cart has items",
      status: { name: "Ready", description: "" },
      priority: { name: "High" },
    },
    assignedToID: "user-001",
    assignmentDate: getRelativeTimestamp(14),
    runs: [
      {
        ID: 10015,
        testRunKey: "DEMO-R-10015",
        testCaseID: 4002,
        status: "Passed",
        executedByID: "user-001",
        executionDate: getRelativeTimestamp(6, 13),
        updatedDate: getRelativeTimestamp(6, 13),
        executionTime: 28000,
        environment: "Production",
        buildNumber: "v2.4.5",
        comment: "Product removed, total price updated",
      },
    ],
  },
  // Day 9 (5 days ago) - More cart tests
  {
    ID: 5016,
    testCase: {
      ID: 4003,
      key: "DEMO-TC-4003",
      title: "Update Product Quantity",
      description: "Test user can change quantity of items in cart",
      precondition: "Cart has items",
      status: { name: "Ready", description: "" },
      priority: { name: "High" },
    },
    assignedToID: "user-001",
    assignmentDate: getRelativeTimestamp(14),
    runs: [
      {
        ID: 10016,
        testRunKey: "DEMO-R-10016",
        testCaseID: 4003,
        status: "Passed",
        executedByID: "user-001",
        executionDate: getRelativeTimestamp(5, 10),
        updatedDate: getRelativeTimestamp(5, 10),
        executionTime: 41000,
        environment: "Production",
        buildNumber: "v2.4.5",
        comment: "Quantity updated, price recalculated correctly",
      },
    ],
  },
  {
    ID: 5017,
    testCase: {
      ID: 4004,
      key: "DEMO-TC-4004",
      title: "Apply Discount Code",
      description: "Test valid discount codes are applied to total",
      precondition: "Cart has items, valid discount code exists",
      status: { name: "Ready", description: "" },
      priority: { name: "Medium" },
    },
    assignedToID: "user-002",
    assignmentDate: getRelativeTimestamp(14),
    runs: [
      {
        ID: 10017,
        testRunKey: "DEMO-R-10017",
        testCaseID: 4004,
        status: "Failed",
        executedByID: "user-002",
        executionDate: getRelativeTimestamp(5, 9),
        updatedDate: getRelativeTimestamp(5, 9),
        executionTime: 56000,
        environment: "Staging",
        buildNumber: "v2.4.5",
        comment: "Discount calculation incorrect for percentage discounts. Bug: DEMO-BUG-228",
      },
    ],
  },
  {
    ID: 5018,
    testCase: {
      ID: 4005,
      key: "DEMO-TC-4005",
      title: "Checkout Flow Complete",
      description: "Test complete checkout process from cart to confirmation",
      precondition: "Cart has items, user logged in with payment method",
      status: { name: "Ready", description: "" },
      priority: { name: "Critical" },
    },
    assignedToID: "user-001",
    assignmentDate: getRelativeTimestamp(14),
    runs: [
      {
        ID: 10018,
        testRunKey: "DEMO-R-10018",
        testCaseID: 4005,
        status: "Passed",
        executedByID: "user-001",
        executionDate: getRelativeTimestamp(5, 8),
        updatedDate: getRelativeTimestamp(5, 8),
        executionTime: 245000,
        environment: "Production",
        buildNumber: "v2.4.5",
        comment: "Order placed successfully, confirmation email sent",
      },
    ],
  },
  // Day 10 (4 days ago) - Search Tests
  {
    ID: 5019,
    testCase: {
      ID: 5001,
      key: "DEMO-TC-5001",
      title: "Product Search by Keyword",
      description: "Test search returns relevant products for keywords",
      precondition: "Products exist in database",
      status: { name: "Ready", description: "" },
      priority: { name: "High" },
    },
    assignedToID: "user-002",
    assignmentDate: getRelativeTimestamp(14),
    runs: [
      {
        ID: 10019,
        testRunKey: "DEMO-R-10019",
        testCaseID: 5001,
        status: "Passed",
        executedByID: "user-002",
        executionDate: getRelativeTimestamp(4, 14),
        updatedDate: getRelativeTimestamp(4, 14),
        executionTime: 123000,
        environment: "Production",
        buildNumber: "v2.4.5",
        comment: "Search results relevant and fast (<1 sec)",
      },
    ],
  },
  {
    ID: 5020,
    testCase: {
      ID: 5002,
      key: "DEMO-TC-5002",
      title: "Filter by Price Range",
      description: "Test products can be filtered by price range",
      precondition: "Products with various prices exist",
      status: { name: "Ready", description: "" },
      priority: { name: "Medium" },
    },
    assignedToID: "user-002",
    assignmentDate: getRelativeTimestamp(14),
    runs: [
      {
        ID: 10020,
        testRunKey: "DEMO-R-10020",
        testCaseID: 5002,
        status: "Passed",
        executedByID: "user-002",
        executionDate: getRelativeTimestamp(4, 13),
        updatedDate: getRelativeTimestamp(4, 13),
        executionTime: 87000,
        environment: "Production",
        buildNumber: "v2.4.5",
        comment: "Filter applied correctly, results match criteria",
      },
    ],
  },
  // Day 11 (3 days ago) - More search tests
  {
    ID: 5021,
    testCase: {
      ID: 5003,
      key: "DEMO-TC-5003",
      title: "Sort Products by Rating",
      description: "Test products can be sorted by customer rating",
      precondition: "Products have ratings",
      status: { name: "Ready", description: "" },
      priority: { name: "Low" },
    },
    assignedToID: "user-002",
    assignmentDate: getRelativeTimestamp(14),
    runs: [
      {
        ID: 10021,
        testRunKey: "DEMO-R-10021",
        testCaseID: 5003,
        status: "Blocked",
        executedByID: "user-002",
        executionDate: getRelativeTimestamp(3, 10),
        updatedDate: getRelativeTimestamp(3, 10),
        executionTime: 0,
        environment: "Staging",
        buildNumber: "v2.4.5",
        comment: "Rating system database migration in progress. Cannot test.",
      },
    ],
  },
  {
    ID: 5022,
    testCase: {
      ID: 5004,
      key: "DEMO-TC-5004",
      title: "Category Filter",
      description: "Test filtering products by category",
      precondition: "Products are categorized",
      status: { name: "Ready", description: "" },
      priority: { name: "High" },
    },
    assignedToID: "user-003",
    assignmentDate: getRelativeTimestamp(14),
    runs: [
      {
        ID: 10022,
        testRunKey: "DEMO-R-10022",
        testCaseID: 5004,
        status: "Passed",
        executedByID: "user-003",
        executionDate: getRelativeTimestamp(3, 9),
        updatedDate: getRelativeTimestamp(3, 9),
        executionTime: 76000,
        environment: "Production",
        buildNumber: "v2.4.5",
        comment: "Category filter working perfectly",
      },
    ],
  },
  // Day 12 (2 days ago) - Regression Tests
  {
    ID: 5023,
    testCase: {
      ID: 6001,
      key: "DEMO-TC-6001",
      title: "Homepage Load Time",
      description: "Test homepage loads within acceptable time",
      precondition: "Application running",
      status: { name: "Ready", description: "" },
      priority: { name: "High" },
    },
    assignedToID: "user-002",
    assignmentDate: getRelativeTimestamp(14),
    runs: [
      {
        ID: 10023,
        testRunKey: "DEMO-R-10023",
        testCaseID: 6001,
        status: "Passed",
        executedByID: "user-002",
        executionDate: getRelativeTimestamp(2, 10),
        updatedDate: getRelativeTimestamp(2, 10),
        executionTime: 45000,
        environment: "Production",
        buildNumber: "v2.5.0",
        comment: "Homepage loads in 1.2 seconds - within SLA",
      },
    ],
  },
  {
    ID: 5024,
    testCase: {
      ID: 6002,
      key: "DEMO-TC-6002",
      title: "Navigation Menu Functionality",
      description: "Test all navigation menu links work correctly",
      precondition: "User on any page",
      status: { name: "Ready", description: "" },
      priority: { name: "Medium" },
    },
    assignedToID: "user-002",
    assignmentDate: getRelativeTimestamp(14),
    runs: [
      {
        ID: 10024,
        testRunKey: "DEMO-R-10024",
        testCaseID: 6002,
        status: "Passed",
        executedByID: "user-002",
        executionDate: getRelativeTimestamp(2, 9),
        updatedDate: getRelativeTimestamp(2, 9),
        executionTime: 123000,
        environment: "Production",
        buildNumber: "v2.5.0",
        comment: "All 15 menu items tested and working",
      },
    ],
  },
  {
    ID: 5025,
    testCase: {
      ID: 6003,
      key: "DEMO-TC-6003",
      title: "Footer Links Verification",
      description: "Test footer links navigate to correct pages",
      precondition: "User on any page",
      status: { name: "Ready", description: "" },
      priority: { name: "Low" },
    },
    assignedToID: "user-003",
    assignmentDate: getRelativeTimestamp(14),
    runs: [
      {
        ID: 10025,
        testRunKey: "DEMO-R-10025",
        testCaseID: 6003,
        status: "Not Run",
        executedByID: "",
        executionDate: 0,
        updatedDate: 0,
        executionTime: 0,
        environment: "",
        buildNumber: "",
        comment: "",
      },
    ],
  },
  // Day 13 (1 day ago) - Security Tests
  {
    ID: 5026,
    testCase: {
      ID: 7001,
      key: "DEMO-TC-7001",
      title: "SQL Injection Prevention",
      description: "Test application prevents SQL injection attacks",
      precondition: "Application endpoints accessible",
      status: { name: "Ready", description: "" },
      priority: { name: "Critical" },
    },
    assignedToID: "user-003",
    assignmentDate: getRelativeTimestamp(14),
    runs: [
      {
        ID: 10026,
        testRunKey: "DEMO-R-10026",
        testCaseID: 7001,
        status: "Passed",
        executedByID: "user-003",
        executionDate: getRelativeTimestamp(1, 10),
        updatedDate: getRelativeTimestamp(1, 10),
        executionTime: 456000,
        environment: "Staging",
        buildNumber: "v2.5.0",
        comment: "All inputs properly sanitized, no vulnerabilities found",
      },
    ],
  },
  {
    ID: 5027,
    testCase: {
      ID: 7002,
      key: "DEMO-TC-7002",
      title: "XSS Attack Prevention",
      description: "Test application prevents cross-site scripting",
      precondition: "Application running",
      status: { name: "Ready", description: "" },
      priority: { name: "Critical" },
    },
    assignedToID: "user-003",
    assignmentDate: getRelativeTimestamp(14),
    runs: [
      {
        ID: 10027,
        testRunKey: "DEMO-R-10027",
        testCaseID: 7002,
        status: "Passed",
        executedByID: "user-003",
        executionDate: getRelativeTimestamp(1, 9),
        updatedDate: getRelativeTimestamp(1, 9),
        executionTime: 389000,
        environment: "Staging",
        buildNumber: "v2.5.0",
        comment: "XSS protection working, scripts escaped properly",
      },
    ],
  },
  {
    ID: 5028,
    testCase: {
      ID: 7003,
      key: "DEMO-TC-7003",
      title: "Session Timeout",
      description: "Test user session expires after inactivity",
      precondition: "User logged in",
      status: { name: "Ready", description: "" },
      priority: { name: "High" },
    },
    assignedToID: "user-003",
    assignmentDate: getRelativeTimestamp(14),
    runs: [
      {
        ID: 10028,
        testRunKey: "DEMO-R-10028",
        testCaseID: 7003,
        status: "Failed",
        executedByID: "user-003",
        executionDate: getRelativeTimestamp(1, 8),
        updatedDate: getRelativeTimestamp(1, 8),
        executionTime: 1805000,
        environment: "Staging",
        buildNumber: "v2.5.0",
        comment: "Session timeout not working properly. Users remain logged in indefinitely. Bug: DEMO-BUG-241",
      },
    ],
  },
  // Day 14 (today) - Performance Tests
  {
    ID: 5029,
    testCase: {
      ID: 8001,
      key: "DEMO-TC-8001",
      title: "Load Test - 1000 Concurrent Users",
      description: "Test system handles 1000 simultaneous users",
      precondition: "Load testing environment ready",
      status: { name: "Ready", description: "" },
      priority: { name: "High" },
    },
    assignedToID: "user-001",
    assignmentDate: getRelativeTimestamp(14),
    runs: [
      {
        ID: 10029,
        testRunKey: "DEMO-R-10029",
        testCaseID: 8001,
        status: "Passed",
        executedByID: "user-001",
        executionDate: getRelativeTimestamp(0, 3),
        updatedDate: getRelativeTimestamp(0, 3),
        executionTime: 3600000,
        environment: "Performance",
        buildNumber: "v2.5.0",
        comment: "System stable under load. Avg response time: 1.8s, Max: 3.2s",
      },
    ],
  },
  {
    ID: 5030,
    testCase: {
      ID: 8002,
      key: "DEMO-TC-8002",
      title: "Database Query Performance",
      description: "Test database queries execute within acceptable time",
      precondition: "Database populated with test data",
      status: { name: "Ready", description: "" },
      priority: { name: "Medium" },
    },
    assignedToID: "user-001",
    assignmentDate: getRelativeTimestamp(14),
    runs: [
      {
        ID: 10030,
        testRunKey: "DEMO-R-10030",
        testCaseID: 8002,
        status: "Not Run",
        executedByID: "",
        executionDate: 0,
        updatedDate: 0,
        executionTime: 0,
        environment: "",
        buildNumber: "",
        comment: "",
      },
    ],
  },
];

// Mock Folders with Statistics
export const mockFoldersWithStats: FolderWithStats[] = [
  {
    ID: 806,
    name: "Performance Testing",
    description: "Performance and load testing",
    parentID: 800,
    cyclesCount: 1,
    passed: 1,
    failed: 0,
    blocked: 0,
    notRun: 1,
  },
  {
    ID: 805,
    name: "Security Testing",
    description: "Security and penetration testing",
    parentID: 800,
    cyclesCount: 1,
    passed: 2,
    failed: 1,
    blocked: 0,
    notRun: 0,
  },
  {
    ID: 804,
    name: "Regression Testing",
    description: "Ongoing regression tests",
    parentID: 800,
    cyclesCount: 1,
    passed: 2,
    failed: 0,
    blocked: 0,
    notRun: 1,
  },
  {
    ID: 801,
    name: "Sprint 15 - Current Sprint",
    description: "Current sprint testing",
    parentID: 800,
    cyclesCount: 3,
    passed: 18,
    failed: 3,
    blocked: 2,
    notRun: 2,
  },
  {
    ID: 802,
    name: "Sprint 14 - Previous Sprint",
    description: "Previous sprint",
    parentID: 800,
    cyclesCount: 2,
    passed: 22,
    failed: 1,
    blocked: 1,
    notRun: 1,
  },
  {
    ID: 803,
    name: "Sprint 13 - Completed",
    description: "Completed sprint",
    parentID: 800,
    cyclesCount: 2,
    passed: 24,
    failed: 0,
    blocked: 0,
    notRun: 0,
  },
];
